
import Head from "next/head";
import Categories from "./components/categories";
import { Inter } from "@next/font/google";
import Navbar from "./components/navbar/index";
import Posts from "@/pages/components/posts";
import Logo from "@/pages/components/logo";

import { TextField, Button } from "@mui/material";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"w-full grid content-center p-10"}>
          <Logo/>
          <Navbar/>

        <h1>Instagram de puno</h1>
          <Categories/>
          <Posts/>
      </main>
    </>
  );
}
